export const sample_foods: any[] = [
    {
        id:'1',
        name: 'Pizza Pepperoni',
        cookTime: '10-20',
        price: 10,
        favorite: false,
        origins: ['italy'],
        stars: 4.5,
        imageUrl: 'assets/food-1.jpg',
        tags: ['FastFood', 'Pizza', 'Lunch'],
      },
      {
        id:'2',
        name: 'Meatball',
        price: 20,
        cookTime: '20-30',
        favorite: true,
        origins: ['persia', 'middle east', 'china'],
        stars: 4.7,
        imageUrl: 'assets/food-2.jpg',
        tags: ['SlowFood', 'Lunch'],
      },
      {
        id:'3',
        name: 'Hamburger',
        price: 5,
        cookTime: '10-15',
        favorite: false,
        origins: ['germany', 'us'],
        stars: 3.5,
        imageUrl: 'assets/food-3.jpg',
        tags: ['FastFood', 'Hamburger'],
      },
      {
        id:'4',
        name: 'Fried Potatoes',
        price: 2,
        cookTime: '15-20',
        favorite: true,
        origins: ['belgium', 'france'],
        stars: 3.3,
        imageUrl: 'assets/food-4.jpg',
        tags: ['FastFood', 'Fry'],
      },
      {
        id:'5',
        name: 'Chicken Soup',
        price: 11,
        cookTime: '40-50',
        favorite: false,
        origins: ['india', 'asia'],
        stars: 3.0,
        imageUrl: 'assets/food-5.jpg',
        tags: ['SlowFood', 'Soup'],
      },
      {
        id:'6',
        name: 'Vegetables Pizza',
        price: 9,
        cookTime: '40-50',
        favorite: false,
        origins: ['italy'],
        stars: 4.0,
        imageUrl: 'assets/food-6.jpg',
        tags: ['FastFood', 'Pizza', 'Lunch'],
      },
];

export const sample_tags: any[] = [
  { name: 'All', count: 6, imageUrl: 'https://loveincstatic.blob.core.windows.net/loveexploring/lovefood-compressor.jpg' },
  { name: 'FastFood', count: 4, imageUrl: 'https://media-cdn.tripadvisor.com/media/photo-s/17/ad/2f/16/double-burger.jpg' },
  { name: 'Pizza', count: 2, imageUrl: 'https://www.saborusa.com/wp-content/uploads/2019/10/Animate-a-disfrutar-una-deliciosa-pizza-de-salchicha-Foto-destacada.png' },
  { name: 'Lunch', count: 3, imageUrl: 'https://images.immediate.co.uk/production/volatile/sites/30/2013/05/HummusBowl-65a0050.jpg' },
  { name: 'SlowFood', count: 2, imageUrl: 'https://www.hogarmania.com/archivos/201809/vapor-XxXx80.jpg' },
  { name: 'Hamburger', count: 1, imageUrl: 'https://cdn.hswstatic.com/gif/americas-favorite-foods-quiz-560126563.jpg' },
  { name: 'Fry', count: 1, imageUrl: 'https://static.toiimg.com/photo/79559185.cms' },
  { name: 'Soup', count: 1, imageUrl: 'https://production-media.gousto.co.uk/cms/mood-image/791---Chinese-Chicken--Sweetcorn-Soup.jpg' },
];